<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>net10.0;net10.0-windows10.0.19041.0</TargetFrameworks>
		
		<UseMaui>true</UseMaui>
		<SingleProject>true</SingleProject>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<TreatWarningsAsErrors>true</TreatWarningsAsErrors>

		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'windows'">10.0.17763.0</SupportedOSPlatformVersion>
		<TargetPlatformMinVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'windows'">10.0.17763.0</TargetPlatformMinVersion>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.EntityFrameworkCore.Design">
		  <PrivateAssets>all</PrivateAssets>
		  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" />
		<PackageReference Include="Microsoft.Maui.Controls" />
		<PackageReference Include="Serilog" />
		<PackageReference Include="Serilog.Enrichers.Process" />
		<PackageReference Include="Serilog.Enrichers.Thread" />
		<PackageReference Include="Serilog.Extensions.Logging" />
		<PackageReference Include="Serilog.Settings.Configuration" />
		<PackageReference Include="Serilog.Sinks.Console" />
		<PackageReference Include="Serilog.Sinks.Debug" />
		<PackageReference Include="Serilog.Sinks.File" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\Nouz.Application\Nouz.Application.csproj" />
	  <ProjectReference Include="..\Nouz.Domain\Nouz.Domain.csproj" />
	  <ProjectReference Include="..\Nouz.ReduxSimple\Nouz.ReduxSimple.csproj" />
	</ItemGroup>

	<ItemGroup>
		<InternalsVisibleTo Include="Nouz.Infrastructure.Unit.Tests" />
		<InternalsVisibleTo Include="DynamicProxyGenAssembly2" />
	</ItemGroup>

	<ItemGroup>
	  <Folder Include="Migrations\" />
	  <Folder Include="Preferences\" />
	</ItemGroup>

</Project>
