<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<TreatWarningsAsErrors>true</TreatWarningsAsErrors>
	</PropertyGroup>

	<ItemGroup>
	  <PackageReference Include="Mediator.Abstractions" />
	  <PackageReference Include="Mediator.SourceGenerator">
	    <PrivateAssets>all</PrivateAssets>
	    <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
	  </PackageReference>
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\Nouz.Domain\Nouz.Domain.csproj" />
	  <ProjectReference Include="..\Nouz.ReduxSimple\Nouz.ReduxSimple.csproj" />
	</ItemGroup>

	<ItemGroup>
		<InternalsVisibleTo Include="Nouz.Application.Unit.Tests" />
		<InternalsVisibleTo Include="DynamicProxyGenAssembly2" />
	</ItemGroup>

	<ItemGroup>
	  <Folder Include="Preferences\" />
	</ItemGroup>

</Project>